import * as t from "@vencord/discord-types";
export declare const Flux: t.Flux;
export type GenericStore = t.FluxStore & Record<string, any>;
export declare const DraftType: any;
export declare let MessageStore: Omit<t.MessageStore, "getMessages"> & GenericStore & {
    getMessages(chanId: string): any;
};
export declare let PermissionStore: t.PermissionStore;
export declare let GuildChannelStore: t.GuildChannelStore;
export declare let ReadStateStore: t.ReadStateStore;
export declare let PresenceStore: t.PresenceStore;
export declare let AccessibilityStore: t.AccessibilityStore;
export declare let GuildStore: t.GuildStore;
export declare let GuildRoleStore: t.GuildRoleStore;
export declare let GuildScheduledEventStore: t.GuildScheduledEventStore;
export declare let GuildMemberCountStore: t.GuildMemberCountStore;
export declare let GuildMemberStore: t.GuildMemberStore;
export declare let UserStore: t.UserStore;
export declare let AuthenticationStore: t.AuthenticationStore;
export declare let ApplicationStore: t.ApplicationStore;
export declare let UserProfileStore: t.UserProfileStore;
export declare let SelectedChannelStore: t.SelectedChannelStore;
export declare let SelectedGuildStore: t.SelectedGuildStore;
export declare let ChannelStore: t.ChannelStore;
export declare let TypingStore: t.TypingStore;
export declare let RelationshipStore: t.RelationshipStore;
export declare let VoiceStateStore: t.VoiceStateStore;
export declare let EmojiStore: t.EmojiStore;
export declare let StickersStore: t.StickersStore;
export declare let ThemeStore: t.ThemeStore;
export declare let WindowStore: t.WindowStore;
export declare let DraftStore: t.DraftStore;
export declare let StreamerModeStore: t.StreamerModeStore;
export declare let SpotifyStore: t.SpotifyStore;
export declare let MediaEngineStore: t.MediaEngineStore;
export declare let NotificationSettingsStore: t.NotificationSettingsStore;
export declare let SpellCheckStore: t.SpellCheckStore;
export declare let UploadAttachmentStore: t.UploadAttachmentStore;
export declare let OverridePremiumTypeStore: t.OverridePremiumTypeStore;
export declare let RunningGameStore: t.RunningGameStore;
export declare let ActiveJoinedThreadsStore: t.ActiveJoinedThreadsStore;
export declare let UserGuildSettingsStore: t.UserGuildSettingsStore;
export declare let UserSettingsProtoStore: t.UserSettingsProtoStore;
export declare let CallStore: t.CallStore;
export declare let ChannelRTCStore: t.ChannelRTCStore;
export declare let FriendsStore: t.FriendsStore;
export declare let InstantInviteStore: t.InstantInviteStore;
export declare let InviteStore: t.InviteStore;
export declare let LocaleStore: t.LocaleStore;
export declare let RTCConnectionStore: t.RTCConnectionStore;
export declare let SoundboardStore: t.SoundboardStore;
export declare let PopoutWindowStore: t.PopoutWindowStore;
/**
 * @see jsdoc of {@link t.useStateFromStores}
 */
export declare const useStateFromStores: t.useStateFromStores;
