import { IShikiTheme } from "@vap/shiki";
export declare const SHIKI_REPO = "shikijs/textmate-grammars-themes";
export declare const SHIKI_REPO_COMMIT = "bc5436518111d87ea58eb56d97b3f9bec30e6b83";
export declare const shikiRepoTheme: (name: string) => string;
export declare const themes: {
    DarkPlus: string;
    MaterialCandy: string;
    Andromeeda: string;
    AuroraX: string;
    AyuDark: string;
    CatppuccinLatte: string;
    CatppuccinFrappe: string;
    CatppuccinMacchiato: string;
    CatppuccinMocha: string;
    DraculaSoft: string;
    Dracula: string;
    EverforestDark: string;
    EverforestLight: string;
    GithubDarkDefault: string;
    GithubDarkDimmed: string;
    GithubDarkHighContrast: string;
    GithubDark: string;
    GithubLightDefault: string;
    GithubLightHighContrast: string;
    GithubLight: string;
    GruvBoxDarkHard: string;
    GruvBoxDarkMedium: string;
    GruvBoxDarkSoft: string;
    GruvBoxLightHard: string;
    GruvBoxLightMedium: string;
    GruvBoxLightSoft: string;
    Houston: string;
    KanagawaDragon: string;
    KanagawaLotus: string;
    KanagawaWave: string;
    LaserWave: string;
    LightPlus: string;
    MaterialDarker: string;
    MaterialDefault: string;
    MaterialLighter: string;
    MaterialOcean: string;
    MaterialPalenight: string;
    MinDark: string;
    MinLight: string;
    Monokai: string;
    NightOwl: string;
    Nord: string;
    OneDarkPro: string;
    OneLight: string;
    Plastic: string;
    Poimandres: string;
    Red: string;
    RosePineDawn: string;
    RosePineMoon: string;
    RosePine: string;
    SlackDark: string;
    SlackOchin: string;
    SnazzyLight: string;
    SolarizedDark: string;
    SolarizedLight: string;
    Synthwave84: string;
    TokyoNight: string;
    Vesper: string;
    VitesseBlack: string;
    VitesseDark: string;
    VitesseLight: string;
};
export declare const themeCache: Map<string, IShikiTheme>;
export declare const getTheme: (url: string) => Promise<IShikiTheme>;
