export declare const SeekBar: import("../../utils/lazyReact").LazyComponentWrapper<import("react").ComponentType<import("react").PropsWithChildren<{
    initialValue: number;
    defaultValue?: number;
    keyboardStep?: number;
    maxValue?: number;
    minValue?: number;
    markers?: number[];
    stickToMarkers?: boolean;
    markerPosition?: 0 | 1;
    orientation?: "horizontal" | "vertical";
    getAriaValueText?(currentValue: number): string;
    renderMarker?(marker: number): import("react").ReactNode;
    onMarkerRender?(marker: number): import("react").ReactNode;
    onValueRender?(value: number): import("react").ReactNode;
    onValueChange?(value: number): void;
    asValueChanges?(value: number): void;
    className?: string;
    disabled?: boolean;
    handleSize?: number;
    mini?: boolean;
    hideBubble?: boolean;
    fillStyles?: import("react").CSSProperties;
    barStyles?: import("react").CSSProperties;
    grabberStyles?: import("react").CSSProperties;
    grabberClassName?: string;
    barClassName?: string;
    "aria-hidden"?: boolean;
    "aria-label"?: string;
    "aria-labelledby"?: string;
    "aria-describedby"?: string;
}>>>;
