import { SVGProps } from "react";
export declare const DiscordIcon: (props: React.PropsWithChildren<SVGProps<SVGSVGElement>>) => import("react").JSX.Element;
export declare const ChromeIcon: (props: React.PropsWithChildren<SVGProps<SVGSVGElement>>) => import("react").JSX.Element;
export declare const EdgeIcon: (props: React.PropsWithChildren<SVGProps<SVGSVGElement>>) => import("react").JSX.Element;
export declare const FirefoxIcon: (props: React.PropsWithChildren<SVGProps<SVGSVGElement>>) => import("react").JSX.Element;
export declare const IEIcon: (props: React.PropsWithChildren<SVGProps<SVGSVGElement>>) => import("react").JSX.Element;
export declare const OperaIcon: (props: React.PropsWithChildren<SVGProps<SVGSVGElement>>) => import("react").JSX.Element;
export declare const SafariIcon: (props: React.PropsWithChildren<SVGProps<SVGSVGElement>>) => import("react").JSX.Element;
export declare const UnknownIcon: (props: React.PropsWithChildren<SVGProps<SVGSVGElement>>) => import("react").JSX.Element;
export declare const MobileIcon: import("../../../utils/react").LazyComponentWrapper<import("react").ComponentType<any>>;
